#pragma once
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

#define MASTER_LEFT
// #define EE_HANDS

#undef TAPPING_TERM
#define TAPPING_TERM 100
#define LONG_TAPPING_TERM 50
#define TAPPING_TERM_PER_KEY

#define PERMISSIVE_HOLD_PER_KEY
//#define IGNORE_MOD_TAP_INTERRUPT_PER_KEY
#define TAPPING_FORCE_HOLD_PER_KEY

#undef TAPPING_TOGGLE
#define TAPPING_TOGGLE 2

#undef  RGBLIGHT_LIMIT_VAL
#define RGBLIGHT_LAYERS
#ifdef RGBLIGHT_ENABLE
    #define RGBLIGHT_EFFECT_BREATHING
    #define RGBLIGHT_EFFECT_RAINBOW_MOOD
    #define RGBLIGHT_EFFECT_RAINBOW_SWIRL
    #define RGBLIGHT_EFFECT_SNAKE
    #define RGBLIGHT_EFFECT_KNIGHT
    #define RGBLIGHT_EFFECT_CHRISTMAS
    #define RGBLIGHT_EFFECT_STATIC_GRADIENT
    #define RGBLIGHT_EFFECT_RGB_TEST
    #define RGBLIGHT_EFFECT_ALTERNATING
    #define RGBLIGHT_EFFECT_TWINKLE
    #define RGBLIGHT_LIMIT_VAL 50
    #define RGBLIGHT_HUE_STEP 10
    #define RGBLIGHT_SAT_STEP 17
    #define RGBLIGHT_VAL_STEP 17
    #define RGBLIGHT_SLEEP 60
    #define RGBLIGHT_SPLIT
    #define RGBLIGHT_DEFAULT_SAT 60
    #define RGBLIGHT_DEFAULT_HUE 0
#endif

#define OLED_FONT_H "keyboards/crkbd/lib/glcdfont.c"
