name: Build QMK

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get -y install git gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi build-essential dfu-util

      - name: Clone QMK firmware repository
        run: |
          git clone https://github.com/qmk/qmk_firmware.git
          cd qmk_firmware
          git submodule add https://github.com/salvavic/qmk_corne_salvavic.git keyboards/crkbd/keymaps/salvavic
          git submodule update --init --recursive

      - name: Build firmware
        run: |
          cd qmk_firmware
          make crkbd:salvavic

      - name: Generate UF2 firmware
        run: |
          cd qmk_firmware
          make crkbd:salvavic:uf2

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware_bin
          path: qmk_firmware/.build/crkbd_rev1_salvavic.hex

      - uses: actions/upload-artifact@v3
        with:
          name: firmware_uf2
          path: qmk_firmware/.build/crkbd_rev1_salvavic.uf2
